# Generated by Django 2.2.2 on 2019-06-19 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oportunidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('local', models.CharField(choices=[('CR', 'CURITIBA'), ('JN', 'JOINVILLE'), ('SP', 'SÃO PAULO'), ('OT', 'OUTRO')], default='CR', max_length=2)),
                ('descricao', models.TextField()),
                ('atribuicao', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('interessados', models.ManyToManyField(related_name='interessados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], default='O', max_length=10)),
                ('dataNascimento', models.DateField()),
                ('estadoCivil', models.CharField(choices=[('Solteiro', 'Solteiro'), ('Casado', 'Casado'), ('Divorsicado', 'Divorsicado'), ('Viuvo', 'Viuvo'), ('Separado', 'Separado')], default='S', max_length=15)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=150)),
                ('cep', models.CharField(max_length=10)),
                ('logradouro', models.CharField(max_length=150)),
                ('numero', models.CharField(max_length=15)),
                ('bairro', models.CharField(max_length=150)),
                ('cidade', models.CharField(max_length=150)),
                ('uf', models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AO', 'AO'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MT'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', ' SP'), ('SE', 'SE'), ('TP', 'TP')], default='AC', max_length=15)),
                ('pais', models.CharField(max_length=150)),
                ('resumoProfissional', models.TextField()),
                ('objetivoProfissional', models.TextField()),
                ('nivelDeFormacao', models.TextField()),
                ('instituicaoDeEnsino', models.CharField(max_length=200)),
                ('curso', models.CharField(max_length=200)),
                ('sitaucao', models.CharField(choices=[('EM ANDAMENTO', 'EM ANDAMENTO'), ('CONCLUIDO', 'CONCLUIDO')], default='AN', max_length=20)),
                ('anoDeConclusao', models.DateField()),
                ('empresa', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=150)),
                ('dataInicial', models.DateField()),
                ('dataFinal', models.DateField()),
                ('atividades', models.TextField()),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
